// SPDX-FileCopyrightText: Copyright (c) 2026 Quadrant contributors
// SPDX-License-Identifier: GPL-3.0-only

// Product semantic aliases; original Microsoft SVG bytes and MIT license retained.
export global ProductIcons {
    out property <image> quadrants_regular: @image-url("../../assets/icons/quadrants-20-regular.svg");
    out property <image> quadrants_filled: @image-url("../../assets/icons/quadrants-20-filled.svg");
    out property <image> today_regular: @image-url("../../assets/icons/today-20-regular.svg");
    out property <image> today_filled: @image-url("../../assets/icons/today-20-filled.svg");
    out property <image> focus_regular: @image-url("../../assets/icons/focus-20-regular.svg");
    out property <image> focus_filled: @image-url("../../assets/icons/focus-20-filled.svg");
    out property <image> review_regular: @image-url("../../assets/icons/review-20-regular.svg");
    out property <image> review_filled: @image-url("../../assets/icons/review-20-filled.svg");
    out property <image> completed_regular: @image-url("../../assets/icons/completed-20-regular.svg");
    out property <image> completed_filled: @image-url("../../assets/icons/completed-20-filled.svg");
    out property <image> restore_task: @image-url("../../assets/icons/restore-task-16-regular.svg");
}
